version: "3.9"

services:
  app:
    container_name: senti1_app
    build: ./app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    networks:
      - back
      - front
  db:
    container_name: senti1_db
    build: ./database
    networks:
      - back

networks:
  back:
    internal: true
  front:
    internal: false
